// Generated by gencpp from file turtlebot3_functionalities/AddTwoInts.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_FUNCTIONALITIES_MESSAGE_ADDTWOINTS_H
#define TURTLEBOT3_FUNCTIONALITIES_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <turtlebot3_functionalities/AddTwoIntsRequest.h>
#include <turtlebot3_functionalities/AddTwoIntsResponse.h>


namespace turtlebot3_functionalities
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace turtlebot3_functionalities


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::turtlebot3_functionalities::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::turtlebot3_functionalities::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::turtlebot3_functionalities::AddTwoInts > {
  static const char* value()
  {
    return "turtlebot3_functionalities/AddTwoInts";
  }

  static const char* value(const ::turtlebot3_functionalities::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::turtlebot3_functionalities::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::turtlebot3_functionalities::AddTwoInts > 
template<>
struct MD5Sum< ::turtlebot3_functionalities::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_functionalities::AddTwoInts >::value();
  }
  static const char* value(const ::turtlebot3_functionalities::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_functionalities::AddTwoIntsRequest> should match 
// service_traits::DataType< ::turtlebot3_functionalities::AddTwoInts > 
template<>
struct DataType< ::turtlebot3_functionalities::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_functionalities::AddTwoInts >::value();
  }
  static const char* value(const ::turtlebot3_functionalities::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::turtlebot3_functionalities::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::turtlebot3_functionalities::AddTwoInts > 
template<>
struct MD5Sum< ::turtlebot3_functionalities::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::turtlebot3_functionalities::AddTwoInts >::value();
  }
  static const char* value(const ::turtlebot3_functionalities::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::turtlebot3_functionalities::AddTwoIntsResponse> should match 
// service_traits::DataType< ::turtlebot3_functionalities::AddTwoInts > 
template<>
struct DataType< ::turtlebot3_functionalities::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::turtlebot3_functionalities::AddTwoInts >::value();
  }
  static const char* value(const ::turtlebot3_functionalities::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TURTLEBOT3_FUNCTIONALITIES_MESSAGE_ADDTWOINTS_H
