// Generated by gencpp from file turtlebot3_functionalities/switchState.msg
// DO NOT EDIT!


#ifndef TURTLEBOT3_FUNCTIONALITIES_MESSAGE_SWITCHSTATE_H
#define TURTLEBOT3_FUNCTIONALITIES_MESSAGE_SWITCHSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtlebot3_functionalities
{
template <class ContainerAllocator>
struct switchState_
{
  typedef switchState_<ContainerAllocator> Type;

  switchState_()
    : state(0)  {
    }
  switchState_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef int64_t _state_type;
  _state_type state;



  enum {
    FORWARD = 8,
    BACK = 2,
    STOP = 5,
    ROTATE_LEFT = 4,
    SQUARE = 69,
  };


  typedef boost::shared_ptr< ::turtlebot3_functionalities::switchState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtlebot3_functionalities::switchState_<ContainerAllocator> const> ConstPtr;

}; // struct switchState_

typedef ::turtlebot3_functionalities::switchState_<std::allocator<void> > switchState;

typedef boost::shared_ptr< ::turtlebot3_functionalities::switchState > switchStatePtr;
typedef boost::shared_ptr< ::turtlebot3_functionalities::switchState const> switchStateConstPtr;

// constants requiring out of line definition

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtlebot3_functionalities::switchState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtlebot3_functionalities::switchState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace turtlebot3_functionalities

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'turtlebot3_functionalities': ['/home/sksuricata/catkin_ws/src/turtlebot3_functionalities/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_functionalities::switchState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtlebot3_functionalities::switchState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_functionalities::switchState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtlebot3_functionalities::switchState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_functionalities::switchState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtlebot3_functionalities::switchState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtlebot3_functionalities::switchState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9db11d2209d4e262a28bf3cb20c338c7";
  }

  static const char* value(const ::turtlebot3_functionalities::switchState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9db11d2209d4e262ULL;
  static const uint64_t static_value2 = 0xa28bf3cb20c338c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::turtlebot3_functionalities::switchState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtlebot3_functionalities/switchState";
  }

  static const char* value(const ::turtlebot3_functionalities::switchState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtlebot3_functionalities::switchState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 state\n\
int64 FORWARD=8\n\
int64 BACK=2\n\
int64 STOP=5\n\
int64 ROTATE_LEFT=4\n\
int64 SQUARE=69\n\
\n\
";
  }

  static const char* value(const ::turtlebot3_functionalities::switchState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtlebot3_functionalities::switchState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct switchState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtlebot3_functionalities::switchState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtlebot3_functionalities::switchState_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int64_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLEBOT3_FUNCTIONALITIES_MESSAGE_SWITCHSTATE_H
